GEMINI_API_KEY = "gen-lang-client-0596119625"
EMAIL_SENDER = "m012417710@gmail.com"
EMAIL_PASSWORD = "your_app_password"
EMAIL_RECEIVER = "receiver@example.com"
TELEGRAM_TOKEN = "8491391031:AAHgKzwYPF_NF38KV2r4ouYF6HYsVO99d0M"
TELEGRAM_CHAT_ID = "863932530"
